### ISSUE TITLE
No Sample Respose to handle response data

### ISSUE THREAD

**Issue by nathanielajayi7** [Flutterwave/rave-java#17]
All examples end with a response without any documentary on how to handle the response information

**Comment by Corvus97** [comment]
Hello @nathanielajayi7,

Thanks for reaching out to the Team.

You can see all responses on our developer documentation - https://developer.flutterwave.com/v2.0/reference#introduction

Please feel free to reach us via our developer forum (https://developer.flutterwave.com/discuss) if you have any additional questions.

Kind regards,
Cornelius
